// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// This file will be automatically regenerated when your Next.js server is running.
/* eslint-disable */

// prettier-ignore
declare module "nextjs-routes" {
  export type Route =
    | { pathname: "/[username]/[collectionId]/[tokenId]"; query: Query<{ "username": string; "collectionId": string; "tokenId": string }> }
    | { pathname: "/[username]/[collectionId]"; query: Query<{ "username": string; "collectionId": string }> }
    | { pathname: "/[username]"; query: Query<{ "username": string }> }
    | { pathname: "/_/components"; query?: Query | undefined }
    | { pathname: "/_/reset"; query?: Query | undefined }
    | { pathname: "/announcements"; query?: Query | undefined }
    | { pathname: "/auth"; query?: Query | undefined }
    | { pathname: "/community/[contractAddress]"; query: Query<{ "contractAddress": string }> }
    | { pathname: "/community/poap/[contractAddress]"; query: Query<{ "contractAddress": string }> }
    | { pathname: "/community/tez/[contractAddress]"; query: Query<{ "contractAddress": string }> }
    | { pathname: "/edit"; query?: Query | undefined }
    | { pathname: "/gallery/[galleryId]/collection/[collectionId]/edit"; query: Query<{ "galleryId": string; "collectionId": string }> }
    | { pathname: "/gallery/[galleryId]/collection/create"; query: Query<{ "galleryId": string }> }
    | { pathname: "/gallery/[galleryId]/edit"; query: Query<{ "galleryId": string }> }
    | { pathname: "/home"; query?: Query | undefined }
    | { pathname: "/"; query?: Query | undefined }
    | { pathname: "/maintenance"; query?: Query | undefined }
    | { pathname: "/members"; query?: Query | undefined }
    | { pathname: "/members/poster"; query?: Query | undefined }
    | { pathname: "/membership/general"; query?: Query | undefined }
    | { pathname: "/membership/gold"; query?: Query | undefined }
    | { pathname: "/membership/silver"; query?: Query | undefined }
    | { pathname: "/nuke"; query?: Query | undefined }
    | { pathname: "/onboarding/add-user-info"; query?: Query | undefined }
    | { pathname: "/onboarding/congratulations"; query?: Query | undefined }
    | { pathname: "/onboarding/create"; query?: Query | undefined }
    | { pathname: "/onboarding/edit-collection"; query?: Query | undefined }
    | { pathname: "/onboarding/organize-collection"; query?: Query | undefined }
    | { pathname: "/onboarding/organize-gallery"; query?: Query | undefined }
    | { pathname: "/onboarding/welcome"; query?: Query | undefined }
    | { pathname: "/opengraph/collection/[collectionId]"; query: Query<{ "collectionId": string }> }
    | { pathname: "/opengraph/nft/[tokenId]"; query: Query<{ "tokenId": string }> }
    | { pathname: "/opengraph/user/[username]"; query: Query<{ "username": string }> }
    | { pathname: "/privacy"; query?: Query | undefined }
    | { pathname: "/shop"; query?: Query | undefined }
    | { pathname: "/terms"; query?: Query | undefined };

  type Query<Params = {}> = Params & { [key: string]: string | string[] | undefined };

  type QueryForPathname = {
    [K in Route as K["pathname"]]: Exclude<K["query"], undefined>;
  };

  export type RoutedQuery<P extends Route["pathname"]> = QueryForPathname[P];

  export type Locale = undefined;
  
  /**
   * A typesafe utility function for generating paths in your application.
   *
   * route({ pathname: '/foos/[foo]', query: { foo: 'bar' }}) will produce '/foos/bar'.
   */
  export declare function route(r: Route): string;
}

// prettier-ignore
declare module "next/link" {
  import type { Route } from "nextjs-routes";
  import type { LinkProps as NextLinkProps } from "next/dist/client/link";
  import type { PropsWithChildren, MouseEventHandler } from "react";
  export * from "next/dist/client/link";

  type RouteOrQuery = Route | { query?: { [key: string]: string | string[] | undefined } };

  export interface LinkProps extends Omit<NextLinkProps, "href" | "locale"> {
    href: RouteOrQuery;
    locale?: false;
  }

  declare function Link(
    props: PropsWithChildren<LinkProps>
  ): DetailedReactHTMLElement<
    {
      onMouseEnter?: MouseEventHandler<Element> | undefined;
      onClick: MouseEventHandler;
      href?: string | undefined;
      ref?: any;
    },
    HTMLElement
  >;

  export default Link;
}

// prettier-ignore
declare module "next/router" {
  import type { Locale, Route, RoutedQuery } from "nextjs-routes";
  import type { NextRouter as Router } from "next/dist/client/router";
  export * from "next/dist/client/router";
  export { default } from "next/dist/client/router";

  type NextTransitionOptions = NonNullable<Parameters<Router["push"]>[2]>;

  interface TransitionOptions extends Omit<NextTransitionOptions, 'locale'> {
    locale?: false;
  };

  type RouteOrQuery = 
    | Route
    | { query: { [key: string]: string | string[] | undefined } };

  export interface NextRouter<P extends Route["pathname"] = Route["pathname"]>
    extends Omit<
      Router,
      "push" | "replace" | "locale" | "locales" | "defaultLocale" | "domainLocales"
    > {
    defaultLocale?: undefined;
    domainLocales?: undefined;
    locale?: Locale;
    locales?: undefined;
    pathname: P;
    push(
      url: RouteOrQuery,
      as?: string,
      options?: TransitionOptions
    ): Promise<boolean>;
    query: RoutedQuery<P>;
    replace(
      url: RouteOrQuery,
      as?: string,
      options?: TransitionOptions
    ): Promise<boolean>;
    route: P;
  }

  export function useRouter<P extends Route["pathname"]>(): NextRouter<P>;
}
