export const COLUMN_COUNT = 3;
export const SIDEBAR_ICON_GAP = 16;
export const SIDEBAR_ICON_DIMENSIONS = 60;
export const SIDEBAR_COLLECTION_TITLE_HEIGHT = 40;
export const SIDEBAR_COLLECTION_TITLE_BOTTOM_SPACE = 12;
