export const COLUMN_COUNT = 3;
export const SIDEBAR_ICON_GAP = 2;
export const SIDEBAR_ICON_DIMENSIONS = 69;
export const SIDEBAR_COLLECTION_TITLE_HEIGHT = 32;
export const SIDEBAR_COLLECTION_TITLE_BOTTOM_SPACE = 12;
