export const INITIAL = Symbol('INITIAL');
export const ADDRESS_ALREADY_CONNECTED = Symbol('ADDRESS_ALREADY_CONNECTED');
export const CONFIRM_ADDRESS = Symbol('CONFIRM_ADDRESS');
export const PROMPT_SIGNATURE = Symbol('PROMPT_SIGNATURE');
