// DO NOT EDIT THIS FILE WITHOUT ALSO EDITING colors.d.ts right next to this file
// DO NOT EDIT THIS FILE WITHOUT ALSO EDITING colors.d.ts right next to this file
// DO NOT EDIT THIS FILE WITHOUT ALSO EDITING colors.d.ts right next to this file
// DO NOT EDIT THIS FILE WITHOUT ALSO EDITING colors.d.ts right next to this file
// DO NOT EDIT THIS FILE WITHOUT ALSO EDITING colors.d.ts right next to this file

const lightMode = {
  offWhite: '#F9F9F9',
  white: '#FEFEFE',
  black: {
    DEFAULT: '#000000',
    500: '#303030',
    600: '#2A2A2A',
    700: '#202020',
    800: '#141414',
    900: '#0C0C0C',
  },
  shadow: '#707070',
  metal: '#9e9e9e',
  faint: '#f2f2f2',
  porcelain: '#e2e2e2',
  hyperBlue: '#001CC1',
  activeBlue: '#0022F0',
  darkModeBlue: '#7597FF',
  error: '#FF6666',
  red: '#F00000',
};

// Any code related to dark mode is here exclusively to support the `base` iFrame embed
// This is very hacky and brittle, so if you're updating it, treat it that way.
const darkMode = {
  black: {
    DEFAULT: '#FFFFFF',
    500: '#303030',
    600: '#2A2A2A',
    700: '#202020',
    800: '#FEFEFE',
    900: '#0C0C0C',
  },
  white: '#000000',
  offWhite: '#141414',
  faint: '#707070',
  metal: '#9e9e9e',
  shadow: '#f2f2f2',
  porcelain: '#e2e2e2',
  hyperBlue: '#2563eb',
  darkModeBlue: '#7597FF',
  activeBlue: '#2563eb',
  error: '#FF6666',
  red: '#F00000',
};

if (isDarkMode()) {
  document.body.style.background = darkMode.white;
  document.body.style.color = darkMode.black;
}

const scheme = isDarkMode() ? darkMode : lightMode;

function isDarkMode() {
  if (typeof window === 'undefined') {
    return false;
  }

  // for some reason `window` is defined on RN but `window.location` is not
  return window.location?.pathname === '/base';
}

module.exports = scheme;
