name: GitHub Actions Demo
on: [push]
# env:
#   KEYBASE_USERNAME: ${{secrets.KEYBASE_USERNAME}}
#   KEYBASE_PAPERKEY: ${{secrets.KEYBASE_PAPER_KEY}}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
      # - name: "Display username"
      #   run: echo ${{secrets.KEYBASE_USERNAME}} | sed 's/./& /g'
      # - name: Install dependencies
      #   run: yarn install
      - name: "Update apt"
        run: sudo apt-get update
      - name: "Download Keybase"
        run: curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
      - name: "Install Keybase"
        run: sudo apt-get install ./keybase_amd64.deb --no-install-recommends
      - name: "Run keybase globally"
        run: run_keybase -g
      - name: "Oneshot Keybase"
        run: keybase oneshot
        env:
          KEYBASE_USERNAME: ${{secrets.KEYBASE_USERNAME}}
          KEYBASE_PAPERKEY: ${{secrets.KEYBASE_PAPER_KEY}}
      - name: "Check file"
        uses: actions/checkout@v1
      - name: "Decrypt secrets"
        run: keybase decrypt -i _encrypted_internal -o _internal.zip
      # - run:
      #     name: "Install cli dependencies"
      #     command: sudo apt-get -y install unzip
      # - run:
      #     name: "Unzip secrets file"
      #     command: echo "A" | unzip _internal.zip -d _internal
