name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
      # - name: Install dependencies
      #   run: yarn install
      - name: "Set ENV variable"
        run: export KEYBASE_USERNAME=${{ secrets.KEYBASE_USERNAME }}
      - name: "Test username"
        run: echo ${{ secrets.KEYBASE_USERNAME }}
      - name: "Set ENV Paperkey variable"
        run: export KEYBASE_PAPERKEY=${{ secrets.KEYBASE_PAPER_KEY }}
      - name: "Update apt"
        run: sudo apt-get update
      - name: "Download Keybase"
        run: curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
      - name: "Install Keybase"
        run: sudo apt-get install ./keybase_amd64.deb --no-install-recommends
      - name: "Run keybase globally"
        run: run_keybase -g
      - name: "Oneshot Keybase --username= ${{ secrets.KEYBASE_USERNAME }}"
        run: "keybase oneshot"
      - name: "Decrypt secrets"
        run: keybase decrypt -i _encrypted_internal -o _internal.zip
      # - run:
      #     name: "Install cli dependencies"
      #     command: sudo apt-get -y install unzip
      # - run:
      #     name: "Unzip secrets file"
      #     command: echo "A" | unzip _internal.zip -d _internal
