name: repo-typecheck
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
      - uses: 'actions/setup-node@v3'
        with:
          node-version: 16.18.1
          cache: 'yarn'
      - run: 'yarn install --immutable'
      - name: Run Typecheck
        run: node_modules/.bin/moon run web:typecheck mobile:typecheck frames:typecheck shared:typecheck
