name: ci
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
      - uses: 'actions/setup-node@v3'
        with:
          node-version: 18.12.0
          cache: 'yarn'
      - run: 'yarn install --immutable'
      - name: Run unit tests
        run: yarn moon run web:codegen && yarn moon run web:test
