name: web-unit
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
      - uses: 'actions/setup-node@v3'
        with:
          node-version: 20.5.0
          cache: 'yarn'
      - run: 'yarn install --immutable'
      - name: Run web unit tests
        run: node_modules/.bin/moon run web:codegen && node_modules/.bin/moon run web:test
      - name: Run shared package tests
        run: node_modules/.bin/moon run shared:relay-codegen && node_modules/.bin/moon run shared:test
