name: screenshots
on: [deployment_status]
jobs:
  # start disable ---
  # temporarily disable workflow as the failure mode is unclear
  # last time this job failed: https://github.com/gallery-so/gallery/actions/runs/3951382775/jobs/6765164811
  if: ${{ false }}
  # --- end disable
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
      - name: install puppeteer-headful
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'

      - name: user-gallery
        working-directory: apps/web
        uses: flameddd/screenshots-ci-action@master
        with:
          url: ${{ github.event.deployment_status.target_url }}/percyio
          devices: iPhone 13,iPad
          fullPage: 'true'
      - uses: actions/upload-artifact@v3
        working-directory: apps/web
        with:
          path: screenshots
          name: user-gallery

      - name: image-detail
        working-directory: apps/web
        uses: flameddd/screenshots-ci-action@master
        with:
          url: ${{ github.event.deployment_status.target_url }}/percyio/26SbJpukOE3AIJuo9JsWGBA6Xk1/294pa8BiADwZo1pnElsrWPfyrnE-test
          devices: iPhone 13,iPad
          fullPage: 'true'
      - uses: actions/upload-artifact@v3
        working-directory: apps/web
        with:
          path: screenshots
          name: image-detail
