name: web-lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
      - uses: 'actions/setup-node@v3'
        with:
          node-version: 16.18.1
          cache: 'yarn'
      - run: 'yarn install --immutable'
      - name: Run Lint
        run: node_modules/.bin/moon run web:lint
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
      - uses: 'actions/setup-node@v3'
        with:
          node-version: 16.18.1
          cache: 'yarn'
      - run: 'yarn install --immutable'
      - name: Run typecheck
        run: node_modules/.bin/moon run web:codegen && node_modules/.bin/moon run web:typecheck